version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeit
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    ports:
      - "80:3000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=changeit
      - PGPORT=5432