version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=changeYourDBPasswordOverHere
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - "80:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - APP_KEY=changeYourKeyOverHere
      - SESSION_EXPIRES_IN=24h # SESSION WILL EXPIRES IN 24 hours
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=changeYourDBPasswordOverHere
      - PGPORT=5432